runtime: python311

entrypoint: gunicorn -b :$PORT main:app

env_variables:
  FLASK_ENV: "production"
  SECRET_KEY: "change-me-in-step-4"
  # Cloud SQL settings (set in Step 4 properly)
  DB_USER: ""
  DB_PASS: ""
  DB_NAME: ""
  DB_HOST: "/cloudsql"
  CLOUD_SQL_CONNECTION_NAME: ""
  # Firestore
  GCP_PROJECT: ""

handlers:
  - url: /static
    static_dir: static
  - url: /.*
    script: auto
